import { JSONData } from "~/src/utils/types";


export type ContinueFn = (input?: JSONData, permit?: JSONData) => Promise<void>;

export interface UIProps {
  id: string, // this is used to generate the key
  type: string, // the key which dispatches to the actual React component via ComponentMap
  permit?: JSONData,
  continueFn: ContinueFn, // generated by RunUI, provides a way for components to advance the run
  [key: string]: JSONData<Function>
};

/**
 * E.g., a choice object provided by the API will look like this
 * {
 *   "text": "the title or the message prompt"
 *   "type": "choices",
 *   "choices": [
 *      {:id "red", :text "hey what do you think of this red is cool"},
 *      {:id "blue", :text "the color of the sky"}
 *    ],
 *   "permit": "foo"
 * }
 *
 *
 */
